language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g ganache-cli
  - ganache-cli &

install:
  - npm install
  - ./basic-client/install.sh
  - ./basic-client/deploy.sh

script:
  - npm test